export default function getAllProducts() {
  return [
    {
      id: "66driving-1-118-FMEN-001",
      slug: "mexico-66driving-118-001-men",
      title: "Nike",
      name: "Sportswear Tech Fleece Windrunner",
      style: "Style: FB7922-063",
      color: "Color: Dark Grey Heather/Black",
      category: "Men's Full-Zip Hoodie",
      categorySlug: "men-clothing",
      price: 1_799_000,
      stock: 100,
      imageUrl: "/assets/img/man1.png",
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/man1.png",
        "/assets/img/man2..png",
        "/assets/img/man2.jpg",
        "/assets/img/man3.jpg",
      ],
      description: `Blending 2 of our most iconic looks, this full-zip hoodie draws design inspiration from our timeless Windrunner jacket, as well as our Tech Fleece jacket. It's designed to feel relaxed through the shoulders, chest and body for an athletic fit you can layer. Our premium, smooth-on-both-sides fleece feels warmer and softer than ever while keeping the same lightweight build you love.`,
    },
    {
      id: "66paraty-1-133-FWOMEN-133",
      slug: "oversized-HF5321-women",
      title: "Nike",
      name: "Sportswear Essential",
      style: "Style: HF5321-133",
      color: "Colour: Sail",
      category: "Women's Oversized Long-Sleeve T-Shirt",
      categorySlug: "women-clothing",
      price: 4_99_000,
      stock: 5,
      imageUrl: `/assets/img/women1.png`,
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/women1.png",
        "/assets/img/women2.png",
        "/assets/img/women3.png",
        "/assets/img/women4.png",
      ],
      description: `With dropped shoulders and heavyweight cotton, this spacious tee might be your new go-to.`,
    },
    {
      id: "t-shirt-1-178-FKIDS-386",
      slug: "sportwear-FZ5178-kids",
      title: "Nike",
      name: "Sportswear",
      style: "Style: FZ5178-386",
      color: "Colour: Oil Green",
      category: "Older Kids' T-Shirt",
      categorySlug: "kids-clothing",
      price: 269_000,
      stock: 50,
      imageUrl: `/assets/img/kids1.png`,
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/kids1.png",
        "/assets/img/kids2.png",
        "/assets/img/kids3.jpg",
        "/assets/img/kids4.png",
      ],
      description: `You can't go wrong with classic Nike style. Made from soft and breathable cotton, this tee has an easy fit that's perfect for all your daily adventures.`,
    },
    {
      id: "mount-1-1365-Fmen-010",
      slug: "swoosh-DX1365-010-men",
      title: "Nike",
      name: "Solo Swoosh",
      style: "Style: DX1365-010",
      color: "Colour: Black/White",
      category: "Men's Fleece Trousers",
      categorySlug: "men-clothing",
      price: 1_199_000,
      stock: 0,
      imageUrl: `/assets/img/celana1.png`,
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/celana1.png",
        "/assets/img/celana2.png",
        "/assets/img/celana3.jpg",
        "/assets/img/celana4.jpg",
      ],
      description: `Celebrate the power and simplicity of the Swoosh. These soft, brushed-fleece trousers are made for comfort and laid-back, nostalgic style. They're roomy through the seat and thighs, then slightly taper to the cuffed ankle. A soft elastic waist and inner drawcord keeps them comfy where it counts, while the embroidered Swoosh on the left thigh gives you a clean, effortless finish.`,
    },
    {
      id: "silver66-1-2422-Fkids-101",
      slug: "nikepro-FV2422-kids",
      title: "Nike",
      name: "Pro",
      style: "Style: FV2422-010",
      color: "Colour: Black/White",
      category: "Kid's Dri-FIT Training Tank Top",
      categorySlug: "kids-clothing",
      price: 379_000,
      stock: 2,
      imageUrl: "/assets/img/tankanak1.png",
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/tankanak1.png",
        "/assets/img/tankanak2.png",
        "/assets/img/tankanak3.jpg",
        "/assets/img/tankanak4.png",
      ],
      description: `Designed to help keep you cool and comfortable when working up a sweat, this cropped tank top pairs perfectly with your favourite high-waisted Nike Pro shorts or leggings. Plus, its soft and smooth sweat-wicking fabric features just the right amount of stretch to help you make big moves in comfort.`,
    },
    {
      id: "niketrail-370-FWOMEN-370",
      slug: "nike-trail-FN5926-370-women",
      title: "Nike",
      name: "Trail",
      style: "Style: FN5926-370",
      color: "Colour: Jade Horizon/Bicoastal",
      category: "Women's Repel UV Running Jacket",
      categorySlug: "women-clothing",
      price: 1_799_000,
      stock: 100,
      imageUrl: "/assets/img/trail1.png",
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/trail1.png",
        "/assets/img/trail2.png",
        "/assets/img/trail3.png",
        "/assets/img/trail4.jpg",
      ],
      description: `Whether you're out for a quick forest jog or a longer mountain run, Nike Trail has the durability and adaptability to help make connecting with your surroundings easier, even in dynamic conditions. With UV protection and a water-repellent finish, this oversized Ripstop jacket has you covered. And when it's time to shed a layer, stash it inside its own pocket and pack it with you so your run doesn't have to stop.`,
    },
    {
      id: "jordan-brooklyn-HJ1365-368-Fwomen-368",
      slug: "broklyn-HJ1365-368-women",
      title: "Nike",
      name: "Jordan Brooklyn Fleece",
      style: "Style: HJ1365-368",
      color: "Colour: Light Dew/White",
      category: "Women's Shorts",
      categorySlug: "women-clothing",
      price: 498_000,
      stock: 10,
      imageUrl: "/assets/img/broklin1.jpg",
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/broklin1.jpg",
        "/assets/img/broklin2.jpg",
        "/assets/img/broklin3.jpg",
        "/assets/img/broklin4.png",
      ],
      description: `Shorts you can reach for any day of the week? Yeah, we've got 'em. Smooth on the outside with unbrushed loops on the inside, these roomy midweight French terry shorts are comfy enough to wear all year long.`,
    },
    {
      id: "brazil-raissue-1-118-Fmen-750",
      slug: "brazil1998-1183C157.750-men",
      title: "Nike",
      name: "Brazil 1998 Reissue",
      style: "Style #: 1183C157.750",
      color: "Colour: Varsity Maize/Pine Green/Lucky Green",
      category: "Men's Nike Football Replica Shirt",
      categorySlug: "men-clothing",
      price: 1_749_000,
      stock: 0,
      imageUrl: "/assets/img/brazil1.png",
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/brazil1.png",
        "/assets/img/brazil2.jpg",
        "/assets/img/brazil3.jpg",
        "/assets/img/brazil4.jpg",
      ],
      description: `This Reissue shirt looks like it came straight from the vault. With signature colours, embroidered logos and other vintage details, this stitch-for-stitch remake pays homage to the iconic shirts Nike made for the 1998 Brazil National team. It also celebrates one of the all-time greats, whose power, pace and skills took the football world by storm the same year.`,
    },
    {
      id: "kids-longsleeve-FZ5555-072-Fmen-072",
      slug: "kids-longsleeve-FZ5555-072-men",
      title: "Nike",
      name: "Sportswear",
      style: "Style: FZ5555-072",
      color: "Colour: Light Bone/White",
      category: "Kid's Long-Sleeve Top",
      categorySlug: "kids-clothing",
      price: 349_000,
      stock: 56,
      imageUrl: "/assets/img/longslev1.png",
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/longslev1.png",
        "/assets/img/longslev2.png",
        "/assets/img/longslev3.jpg",
        "/assets/img/longslev4.png",
      ],
      description: `Some might see this stretchy, long-sleeve top as basic. But not us. We see it as being full of potential. Its lightweight fabric pulls sweat away from your skin to help you stay dry. Plus, the mock-neck design and form-fitting cut make layering a breeze, giving you plenty of ways to play with your style.`,
    },
  ];
}
